### ISSUE TITLE
Upgrade Packages

### ISSUE THREAD

**Issue by gbourne1** [creativetimofficial/now-ui-dashboard-react#1]
The following packages when upgraded are not compatible. Could you support the latest versions?

◯ node-sass  4.6.1  ❯  4.8.3  https://github.com/sass/node-sass
◯ node-sass-chokidar  0.0.3  ❯  1.2.2  https://github.com/michaelwayman/node-sass-chokidar#readme

**Comment by EINazare** [comment]
Hello @gbourne1 ,

We used those components because they work fine with our scss.
Upgrading them would mean to make major changes to our scss, and unfortunately our team that works over scss doesn't have time for those changes yet.
This being said, we do plan on migrating our scss to the latest rules of scss, but will take some time.
So for now you can either use the packages as they are in our products, or if you really need the latest versions, you would need to upgrade our scss to the newest rules.

Best,
Manu
